# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb49208f806430d7c4e39b914be9a18a"
name = "Napoleon3"
application_url = "http://localhost:3000"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders"
optional_scopes = []
use_legacy_install_flow = true

[auth]
redirect_urls = [ "http://localhost:3000/api/auth/shopify/v2/callback" ]
