// Hook for managing products
'use client';

import { useState, useEffect } from 'react';
import type { ProductWithPricing, ProductFilter } from '../types';

// Mock data for now - will be replaced with actual Shopify data
const mockProducts: ProductWithPricing[] = [
  {
    id: '1',
    title: 'Classic Cotton T-Shirt',
    handle: 'classic-tshirt',
    description: 'Comfortable cotton t-shirt',
    vendor: 'Your Store',
    productType: 'Apparel',
    tags: ['clothing', 'bestseller'],
    status: 'active',
    images: [{
      id: 'img1',
      productId: '1',
      src: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab',
      width: 800,
      height: 800,
    }],
    variants: [
      {
        id: 'var1-black',
        productId: '1',
        title: 'Black / Small',
        sku: 'TSHIRT-BLACK-S',
        price: '29.99',
        compareAtPrice: '34.99',
        inventoryQuantity: 25,
        weight: 180,
        weightUnit: 'g' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var1-black-m',
        productId: '1',
        title: 'Black / Medium',
        sku: 'TSHIRT-BLACK-M',
        price: '29.99',
        compareAtPrice: '34.99',
        inventoryQuantity: 30,
        weight: 200,
        weightUnit: 'g' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var1-white',
        productId: '1',
        title: 'White / Small',
        sku: 'TSHIRT-WHITE-S',
        price: '27.99',
        compareAtPrice: '34.99',
        inventoryQuantity: 20,
        weight: 180,
        weightUnit: 'g' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var1-white-m',
        productId: '1',
        title: 'White / Medium',
        sku: 'TSHIRT-WHITE-M',
        price: '27.99',
        compareAtPrice: '34.99',
        inventoryQuantity: 35,
        weight: 200,
        weightUnit: 'g' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var1-blue',
        productId: '1',
        title: 'Navy Blue / Small',
        sku: 'TSHIRT-BLUE-S',
        price: '31.99',
        compareAtPrice: '37.99',
        inventoryQuantity: 15,
        weight: 180,
        weightUnit: 'g' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var1-blue-m',
        productId: '1',
        title: 'Navy Blue / Medium',
        sku: 'TSHIRT-BLUE-M',
        price: '31.99',
        compareAtPrice: '37.99',
        inventoryQuantity: 28,
        weight: 200,
        weightUnit: 'g' as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 29.99,
      cost: 15.00,
      maxPrice: 45.00,
      currentPrice: 29.99,
      profitMargin: 49.97,
      lastUpdated: new Date(),
    },
  },
  {
    id: '2',
    title: 'Premium Denim Jeans',
    handle: 'premium-jeans',
    description: 'High-quality denim jeans',
    vendor: 'Your Store',
    productType: 'Apparel',
    tags: ['clothing', 'premium'],
    status: 'active',
    images: [{
      id: 'img2',
      productId: '2',
      src: 'https://images.unsplash.com/photo-1542272604-787c3835535d',
      width: 800,
      height: 800,
    }],
    variants: [
      {
        id: 'var2-28',
        productId: '2',
        title: '28 x 30',
        sku: 'JEANS-28-30',
        price: '89.99',
        compareAtPrice: '99.99',
        inventoryQuantity: 15,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var2-30',
        productId: '2',
        title: '30 x 30',
        sku: 'JEANS-30-30',
        price: '89.99',
        compareAtPrice: '99.99',
        inventoryQuantity: 22,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var2-32',
        productId: '2',
        title: '32 x 32',
        sku: 'JEANS-32-32',
        price: '89.99',
        compareAtPrice: '99.99',
        inventoryQuantity: 28,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var2-34',
        productId: '2',
        title: '34 x 32',
        sku: 'JEANS-34-32',
        price: '89.99',
        compareAtPrice: '99.99',
        inventoryQuantity: 18,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var2-36',
        productId: '2',
        title: '36 x 34',
        sku: 'JEANS-36-34',
        price: '89.99',
        compareAtPrice: '99.99',
        inventoryQuantity: 12,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 89.99,
      cost: 45.00,
      maxPrice: 120.00,
      currentPrice: 94.99,
      profitMargin: 52.64,
      lastUpdated: new Date(),
    },
  },
  {
    id: '3',
    title: 'Leather Wallet',
    handle: 'leather-wallet',
    description: 'Genuine leather bifold wallet',
    vendor: 'Leather Goods Co',
    productType: 'Accessories',
    tags: ['accessories', 'leather', 'bestseller'],
    status: 'active',
    images: [{
      id: 'img3',
      productId: '3',
      src: 'https://images.unsplash.com/photo-1627123424574-724758594e93',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var3',
      productId: '3',
      title: 'Default',
      sku: 'WALLET-001',
      price: '49.99',
      inventoryQuantity: 75,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 49.99,
      cost: 20.00,
      maxPrice: 65.00,
      currentPrice: 49.99,
      profitMargin: 59.99,
      lastUpdated: new Date(),
    },
  },
  {
    id: '4',
    title: 'Wireless Headphones',
    handle: 'wireless-headphones',
    description: 'Premium noise-cancelling headphones',
    vendor: 'Tech Audio',
    productType: 'Electronics',
    tags: ['electronics', 'audio', 'premium'],
    status: 'active',
    images: [{
      id: 'img4',
      productId: '4',
      src: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var4',
      productId: '4',
      title: 'Default',
      sku: 'HEADPHONES-001',
      price: '199.99',
      inventoryQuantity: 30,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 199.99,
      cost: 80.00,
      maxPrice: 249.99,
      currentPrice: 189.99,
      profitMargin: 57.90,
      lastUpdated: new Date(),
    },
  },
  {
    id: '5',
    title: 'Sports Water Bottle',
    handle: 'sports-water-bottle',
    description: 'Insulated stainless steel water bottle',
    vendor: 'FitGear',
    productType: 'Sports & Fitness',
    tags: ['fitness', 'sports', 'bestseller'],
    status: 'active',
    images: [{
      id: 'img5',
      productId: '5',
      src: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var5',
      productId: '5',
      title: 'Default',
      sku: 'BOTTLE-001',
      price: '24.99',
      inventoryQuantity: 150,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 24.99,
      cost: 8.00,
      maxPrice: 34.99,
      currentPrice: 27.99,
      profitMargin: 71.42,
      lastUpdated: new Date(),
    },
  },
  {
    id: '6',
    title: 'Canvas Backpack',
    handle: 'canvas-backpack',
    description: 'Durable canvas backpack for everyday use',
    vendor: 'Urban Gear',
    productType: 'Bags',
    tags: ['bags', 'travel'],
    status: 'active',
    images: [{
      id: 'img6',
      productId: '6',
      src: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62',
      width: 800,
      height: 800,
    }],
    variants: [
      {
        id: 'var6-black',
        productId: '6',
        title: 'Black',
        sku: 'BACKPACK-BLACK',
        price: '59.99',
        compareAtPrice: '69.99',
        inventoryQuantity: 25,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var6-gray',
        productId: '6',
        title: 'Gray',
        sku: 'BACKPACK-GRAY',
        price: '59.99',
        compareAtPrice: '69.99',
        inventoryQuantity: 18,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var6-navy',
        productId: '6',
        title: 'Navy Blue',
        sku: 'BACKPACK-NAVY',
        price: '59.99',
        compareAtPrice: '69.99',
        inventoryQuantity: 22,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 59.99,
      cost: 25.00,
      maxPrice: 79.99,
      currentPrice: 59.99,
      profitMargin: 58.33,
      lastUpdated: new Date(),
    },
  },
  {
    id: '7',
    title: 'Smart Watch',
    handle: 'smart-watch',
    description: 'Fitness tracking smart watch',
    vendor: 'Tech Wear',
    productType: 'Electronics',
    tags: ['electronics', 'wearables', 'fitness'],
    status: 'active',
    images: [{
      id: 'img7',
      productId: '7',
      src: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var7',
      productId: '7',
      title: 'Default',
      sku: 'WATCH-001',
      price: '299.99',
      inventoryQuantity: 25,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 299.99,
      cost: 120.00,
      maxPrice: 399.99,
      currentPrice: 299.99,
      profitMargin: 60.00,
      lastUpdated: new Date(),
    },
  },
  {
    id: '8',
    title: 'Running Shoes',
    handle: 'running-shoes',
    description: 'Lightweight performance running shoes',
    vendor: 'SportsPro',
    productType: 'Footwear',
    tags: ['shoes', 'sports', 'running', 'bestseller'],
    status: 'active',
    images: [{
      id: 'img8',
      productId: '8',
      src: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
      width: 800,
      height: 800,
    }],
    variants: [
      {
        id: 'var8-7',
        productId: '8',
        title: 'Size 7 / Black',
        sku: 'SHOES-7-BLACK',
        price: '129.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 12,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var8-8',
        productId: '8',
        title: 'Size 8 / Black',
        sku: 'SHOES-8-BLACK',
        price: '129.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 18,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var8-9',
        productId: '8',
        title: 'Size 9 / Black',
        sku: 'SHOES-9-BLACK',
        price: '129.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 25,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var8-10',
        productId: '8',
        title: 'Size 10 / Black',
        sku: 'SHOES-10-BLACK',
        price: '129.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 22,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var8-7-white',
        productId: '8',
        title: 'Size 7 / White',
        sku: 'SHOES-7-WHITE',
        price: '134.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 10,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var8-8-white',
        productId: '8',
        title: 'Size 8 / White',
        sku: 'SHOES-8-WHITE',
        price: '134.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 15,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'var8-9-white',
        productId: '8',
        title: 'Size 9 / White',
        sku: 'SHOES-9-WHITE',
        price: '134.99',
        compareAtPrice: '149.99',
        inventoryQuantity: 20,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 129.99,
      cost: 55.00,
      maxPrice: 159.99,
      currentPrice: 129.99,
      profitMargin: 57.68,
      lastUpdated: new Date(),
    },
  },
  {
    id: '9',
    title: 'Sunglasses',
    handle: 'sunglasses',
    description: 'Polarized UV protection sunglasses',
    vendor: 'EyeStyle',
    productType: 'Accessories',
    tags: ['accessories', 'eyewear', 'summer'],
    status: 'active',
    images: [{
      id: 'img9',
      productId: '9',
      src: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var9',
      productId: '9',
      title: 'Default',
      sku: 'GLASSES-001',
      price: '79.99',
      inventoryQuantity: 80,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 79.99,
      cost: 30.00,
      maxPrice: 99.99,
      currentPrice: 79.99,
      profitMargin: 62.49,
      lastUpdated: new Date(),
    },
  },
  {
    id: '10',
    title: 'Yoga Mat',
    handle: 'yoga-mat',
    description: 'Non-slip premium yoga mat',
    vendor: 'FitGear',
    productType: 'Sports & Fitness',
    tags: ['fitness', 'yoga', 'wellness'],
    status: 'active',
    images: [{
      id: 'img10',
      productId: '10',
      src: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var10',
      productId: '10',
      title: 'Default',
      sku: 'MAT-001',
      price: '39.99',
      inventoryQuantity: 90,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 39.99,
      cost: 12.00,
      maxPrice: 54.99,
      currentPrice: 42.99,
      profitMargin: 72.09,
      lastUpdated: new Date(),
    },
  },
  {
    id: '11',
    title: 'Coffee Mug Set',
    handle: 'coffee-mug-set',
    description: 'Ceramic coffee mug set of 4',
    vendor: 'HomeStyle',
    productType: 'Home & Kitchen',
    tags: ['kitchen', 'drinkware'],
    status: 'active',
    images: [{
      id: 'img11',
      productId: '11',
      src: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var11',
      productId: '11',
      title: 'Default',
      sku: 'MUG-001',
      price: '34.99',
      inventoryQuantity: 100,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 34.99,
      cost: 14.00,
      maxPrice: 44.99,
      currentPrice: 34.99,
      profitMargin: 59.99,
      lastUpdated: new Date(),
    },
  },
  {
    id: '12',
    title: 'Desk Lamp',
    handle: 'desk-lamp',
    description: 'LED desk lamp with adjustable brightness',
    vendor: 'LightCo',
    productType: 'Home & Office',
    tags: ['lighting', 'office'],
    status: 'active',
    images: [{
      id: 'img12',
      productId: '12',
      src: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var12',
      productId: '12',
      title: 'Default',
      sku: 'LAMP-001',
      price: '44.99',
      inventoryQuantity: 45,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 44.99,
      cost: 18.00,
      maxPrice: 59.99,
      currentPrice: 44.99,
      profitMargin: 59.99,
      lastUpdated: new Date(),
    },
  },
  {
    id: '13',
    title: 'Phone Case',
    handle: 'phone-case',
    description: 'Protective silicone phone case',
    vendor: 'TechGuard',
    productType: 'Electronics',
    tags: ['accessories', 'phone', 'bestseller'],
    status: 'active',
    images: [{
      id: 'img13',
      productId: '13',
      src: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var13',
      productId: '13',
      title: 'Default',
      sku: 'CASE-001',
      price: '19.99',
      inventoryQuantity: 200,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 19.99,
      cost: 5.00,
      maxPrice: 29.99,
      currentPrice: 22.99,
      profitMargin: 78.26,
      lastUpdated: new Date(),
    },
  },
  {
    id: '14',
    title: 'Notebook Set',
    handle: 'notebook-set',
    description: 'Premium lined notebooks - pack of 3',
    vendor: 'Stationery Plus',
    productType: 'Stationery',
    tags: ['office', 'writing'],
    status: 'active',
    images: [{
      id: 'img14',
      productId: '14',
      src: 'https://images.unsplash.com/photo-1544816155-12df9643f363',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var14',
      productId: '14',
      title: 'Default',
      sku: 'NOTEBOOK-001',
      price: '14.99',
      inventoryQuantity: 120,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 14.99,
      cost: 4.00,
      maxPrice: 19.99,
      currentPrice: 14.99,
      profitMargin: 73.32,
      lastUpdated: new Date(),
    },
  },
  {
    id: '15',
    title: 'Bluetooth Speaker',
    handle: 'bluetooth-speaker',
    description: 'Portable waterproof bluetooth speaker',
    vendor: 'Audio Pro',
    productType: 'Electronics',
    tags: ['electronics', 'audio', 'portable'],
    status: 'active',
    images: [{
      id: 'img15',
      productId: '15',
      src: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var15',
      productId: '15',
      title: 'Default',
      sku: 'SPEAKER-001',
      price: '69.99',
      inventoryQuantity: 55,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 69.99,
      cost: 28.00,
      maxPrice: 89.99,
      currentPrice: 74.99,
      profitMargin: 62.66,
      lastUpdated: new Date(),
    },
  },
  {
    id: '16',
    title: 'Travel Pillow',
    handle: 'travel-pillow',
    description: 'Memory foam travel neck pillow',
    vendor: 'ComfortZone',
    productType: 'Travel',
    tags: ['travel', 'comfort'],
    status: 'active',
    images: [{
      id: 'img16',
      productId: '16',
      src: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var16',
      productId: '16',
      title: 'Default',
      sku: 'PILLOW-001',
      price: '29.99',
      inventoryQuantity: 70,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 29.99,
      cost: 10.00,
      maxPrice: 39.99,
      currentPrice: 29.99,
      profitMargin: 66.67,
      lastUpdated: new Date(),
    },
  },
  {
    id: '17',
    title: 'Premium Smartphone Holder',
    handle: 'premium-smartphone-holder',
    description: 'Adjustable phone mount for desk or car',
    vendor: 'TechGuard',
    productType: 'Accessories',
    tags: ['accessories', 'phone', 'car'],
    status: 'active',
    images: [{
      id: 'img17',
      productId: '17',
      src: 'https://images.unsplash.com/photo-1556656793-08538906a9f8',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var17',
      productId: '17',
      title: 'Default',
      sku: 'HOLDER-001',
      price: '24.99',
      inventoryQuantity: 85,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 24.99,
      cost: 8.00,
      maxPrice: 34.99,
      currentPrice: 24.99,
      profitMargin: 67.99,
      lastUpdated: new Date(),
    },
  },
  {
    id: '18',
    title: 'Wireless Charging Pad',
    handle: 'wireless-charging-pad',
    description: 'Fast wireless charger for smartphones and watches',
    vendor: 'TechPower',
    productType: 'Electronics',
    tags: ['electronics', 'charging', 'wireless'],
    status: 'active',
    images: [{
      id: 'img18',
      productId: '18',
      src: 'https://images.unsplash.com/photo-1591290619762-aa4d4a67d5a8',
      width: 800,
      height: 800,
    }],
    variants: [{
      id: 'var18',
      productId: '18',
      title: 'Default',
      sku: 'CHARGER-001',
      price: '39.99',
      inventoryQuantity: 60,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pricing: {
      basePrice: 39.99,
      cost: 15.00,
      maxPrice: 54.99,
      currentPrice: 39.99,
      profitMargin: 62.49,
      lastUpdated: new Date(),
    },
  },
];

export function useProducts(filter?: ProductFilter) {
  const [products, setProducts] = useState<ProductWithPricing[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate API call
    setLoading(true);
    setTimeout(() => {
      let filtered = [...mockProducts];

      // Apply filters
      if (filter?.search) {
        const searchLower = filter.search.toLowerCase();
        filtered = filtered.filter(p =>
          p.title.toLowerCase().includes(searchLower) ||
          p.description.toLowerCase().includes(searchLower)
        );
      }

      if (filter?.tags && filter.tags.length > 0) {
        filtered = filtered.filter(p =>
          filter.tags!.some(tag => p.tags.includes(tag))
        );
      }

      if (filter?.status) {
        filtered = filtered.filter(p => p.status === filter.status);
      }

      // Apply sorting
      if (filter?.sortBy) {
        filtered.sort((a, b) => {
          let aVal, bVal;
          switch (filter.sortBy) {
            case 'title':
              aVal = a.title;
              bVal = b.title;
              break;
            case 'price':
              aVal = a.pricing.currentPrice;
              bVal = b.pricing.currentPrice;
              break;
            case 'updated':
              aVal = new Date(a.updatedAt).getTime();
              bVal = new Date(b.updatedAt).getTime();
              break;
            default:
              aVal = a.title;
              bVal = b.title;
          }

          if (filter.sortDirection === 'desc') {
            return aVal > bVal ? -1 : 1;
          }
          return aVal < bVal ? -1 : 1;
        });
      }

      setProducts(filtered);
      setLoading(false);
    }, 500);
  }, [filter]);

  return { products, loading };
}
